using UnityEngine;
using System.Collections.Generic;

//Do not edit this file directly. To edit this file, use the visual editor window.

public static class GameInput {
public static Vector2 MousePosition { get { return new Vector2(Input.mousePosition.x, Input.mousePosition.y); } }
public static float MouseSensitivity = 0.05f;
public static float ScrollWheelSensitivity = 0.25f;

public static List<AllKeysButtonsAndAxes> ExclusionList = new List<AllKeysButtonsAndAxes>( new AllKeysButtonsAndAxes[] {  } );

public static CombineInputsArray Up = new CombineInputsArray(new CombineInputs(PlayerIndex.One, "Up", AllKeysButtonsAndAxes.Left_Stick_Vertical, AllKeysButtonsAndAxes.W), new CombineInputs(PlayerIndex.Two, "Up", AllKeysButtonsAndAxes.Left_Stick_Vertical), new CombineInputs(PlayerIndex.Three, "Up", AllKeysButtonsAndAxes.Left_Stick_Vertical), new CombineInputs(PlayerIndex.Four, "Up", AllKeysButtonsAndAxes.Left_Stick_Vertical));
public static CombineInputsArray Down = new CombineInputsArray(new CombineInputs(PlayerIndex.One, "Down", AllKeysButtonsAndAxes.Left_Stick_Vertical, AllKeysButtonsAndAxes.S), new CombineInputs(PlayerIndex.Two, "Down", AllKeysButtonsAndAxes.Left_Stick_Vertical), new CombineInputs(PlayerIndex.Three, "Down", AllKeysButtonsAndAxes.Left_Stick_Vertical), new CombineInputs(PlayerIndex.Four, "Down", AllKeysButtonsAndAxes.Left_Stick_Vertical));
public static CombineInputsArray Left = new CombineInputsArray(new CombineInputs(PlayerIndex.One, "Left", AllKeysButtonsAndAxes.Left_Stick_Horizontal, AllKeysButtonsAndAxes.A), new CombineInputs(PlayerIndex.Two, "Left", AllKeysButtonsAndAxes.Left_Stick_Horizontal), new CombineInputs(PlayerIndex.Three, "Left", AllKeysButtonsAndAxes.Left_Stick_Horizontal), new CombineInputs(PlayerIndex.Four, "Left", AllKeysButtonsAndAxes.Left_Stick_Horizontal));
public static CombineInputsArray Right = new CombineInputsArray(new CombineInputs(PlayerIndex.One, "Right", AllKeysButtonsAndAxes.Left_Stick_Horizontal, AllKeysButtonsAndAxes.D), new CombineInputs(PlayerIndex.Two, "Right", AllKeysButtonsAndAxes.Left_Stick_Horizontal), new CombineInputs(PlayerIndex.Three, "Right", AllKeysButtonsAndAxes.Left_Stick_Horizontal), new CombineInputs(PlayerIndex.Four, "Right", AllKeysButtonsAndAxes.Left_Stick_Horizontal));
public static CombineInputsArray Walk = new CombineInputsArray(new CombineInputs(PlayerIndex.One, "Walk", AllKeysButtonsAndAxes.LeftShift, AllKeysButtonsAndAxes.GamePad_B), null, null, null);
public static CombineInputsArray Hide = new CombineInputsArray(new CombineInputs(PlayerIndex.One, "Hide", AllKeysButtonsAndAxes.F, AllKeysButtonsAndAxes.GamePad_X), null, null, null);
public static CombineInputsArray Dodge = new CombineInputsArray(new CombineInputs(PlayerIndex.One, "Dodge", AllKeysButtonsAndAxes.Space, AllKeysButtonsAndAxes.GamePad_Y), null, null, null);
public static CombineInputsArray FireWeapon = new CombineInputsArray(new CombineInputs(PlayerIndex.One, "FireWeapon", AllKeysButtonsAndAxes.Mouse_Button_Left, AllKeysButtonsAndAxes.Left_Trigger), null, null, null);
public static CombineInputsArray ChangeWeaponUp = new CombineInputsArray(new CombineInputs(PlayerIndex.One, "ChangeWeaponUp", AllKeysButtonsAndAxes.GamePad_X, AllKeysButtonsAndAxes.Right_Shoulder), null, null, null);
public static CombineInputsArray ChangeWeaponDown = new CombineInputsArray(new CombineInputs(PlayerIndex.One, "ChangeWeaponDown", AllKeysButtonsAndAxes.Scroll_Wheel, AllKeysButtonsAndAxes.Left_Shoulder), null, null, null);
public static CombineInputsArray _AimVertical = new CombineInputsArray(new CombineInputs(PlayerIndex.One, "_AimVertical", AllKeysButtonsAndAxes.Right_Stick_Vertical), null, null, null);
public static CombineInputsArray _AimHorizontal = new CombineInputsArray(new CombineInputs(PlayerIndex.One, "_AimHorizontal", AllKeysButtonsAndAxes.Right_Stick_Horizontal), null, null, null);
public static InputAxisArray Vertical = new InputAxisArray(new InputAxis(PlayerIndex.One, Up[PlayerIndex.One], Down[PlayerIndex.One]), new InputAxis(PlayerIndex.Two, Up[PlayerIndex.Two], Down[PlayerIndex.Two]), new InputAxis(PlayerIndex.Three, Up[PlayerIndex.Three], Down[PlayerIndex.Three]), new InputAxis(PlayerIndex.Four, Up[PlayerIndex.Four], Down[PlayerIndex.Four]));
public static InputAxisArray Horizontal = new InputAxisArray(new InputAxis(PlayerIndex.One, Right[PlayerIndex.One], Left[PlayerIndex.One]), new InputAxis(PlayerIndex.Two, Right[PlayerIndex.Two], Left[PlayerIndex.Two]), new InputAxis(PlayerIndex.Three, Right[PlayerIndex.Three], Left[PlayerIndex.Three]), new InputAxis(PlayerIndex.Four, Right[PlayerIndex.Four], Left[PlayerIndex.Four]));
public static InputAxisArray ChangeWeapon = new InputAxisArray(new InputAxis(PlayerIndex.One, ChangeWeaponUp[PlayerIndex.One], ChangeWeaponDown[PlayerIndex.One]), null, null, null);
public static InputAxisArray AimVertical = new InputAxisArray(new InputAxis(PlayerIndex.One, _AimVertical[PlayerIndex.One], _AimVertical[PlayerIndex.One]), null, null, null);
public static InputAxisArray AimHorizontal = new InputAxisArray(new InputAxis(PlayerIndex.One, _AimHorizontal[PlayerIndex.One], _AimHorizontal[PlayerIndex.One]), null, null, null);
}